### ISSUE TITLE
Relation to StackSTAC

### ISSUE THREAD

**Issue by j08lue** [jsignell/xpystac#5]
I know this project has just started, but it would be great to understand how it relates to [StackSTAC](https://github.com/gjoseph92/stackstac). As far as I can see, both take pySTAC queries and return xarray Datasets, but are different in many other ways. Maybe a note in the README on that - when appropriate?

**Comment by jsignell** [comment]
Yeah thanks for taking a look Jonas! The difference is really in discoverability and invocation. The idea is that as long as this library is in your env, you never need to think about it. You can just use `xarray.open_dataset` on pystac objects and the right thing will just happen. Under the hood this library maps the open to the correct library (stackstac, or back to xarray.open_dataset but with some kwargs pulled from the stac object). I will work on making that clearer in the README.
